### ISSUE TITLE
Stata installation error

### ISSUE THREAD

**Issue by ericmelse** [wbuchanan/brewscheme#16]
Dear William,

I have tried to install using your instruction:
net inst brewscheme, from("http://wbuchanan.github.io/brewscheme/") replace
But, I get the error back from Stata:

file http://wbuchanan.github.io/brewscheme/brewcolors.ado not found
could not copy http://wbuchanan.github.io/brewscheme/brewcolors.ado
(no action taken)

After that, I tried to install manually using your Github files, and was somewhat succesful installing the two foldes brewcolors and style under C:\ado\personal\
but I am not sure if the whole system operates as designed by you.

Can you check the net install on your server (and should I re-install)?

Best regards,
Eric

**Comment by wbuchanan** [comment]
The installation issue should be resolved now. Installing this way is actually pulling the dev branch versions of the files.  It shouldn't be an issue where the .ado files are located as long as they are somewhere on the ADOPATH.
