### ISSUE TITLE
file c:\ado\personal/b/brewmeta.dta not found

### ISSUE THREAD

**Issue by ericmelse** [wbuchanan/brewscheme#17]
Dear William,

I am trying to create the scheme(ggtest2) with brewscheme, but I run into some issues using your file: brewtheme.do
Running the section:
// Generate the theme file used to simulate ggplot2 aesthetics
etc.

I get the error:
file c:\ado\personal/b/brewmeta.dta not found

and indeed that folder is on my drive, but empty.
I check all the do files and explanations on your pages, but failed to find either the file brewmeta.dta itself, or how to create it.

Subsequently, I cannot "brewscheme, scheme(ggtest2)" and run your examples (which would be great to do).

Please advise.
Eric

**Comment by ericmelse** [comment]
Dear William,

I just read your email, and, you are right, after updating using net install, the above reported problems are solved automatically. I.e. the brewmeta.dta file is created and subsequently I was able to create the ggplot2 theme and run your examples (very cool)!

Thus, issue closed.

**Comment by wbuchanan** [comment]
Awesome.  I always forget to test things enough on Windoze (nothing against the users, just not a fan of the platform), but glad to hear things are working for you.  And thank you for being so active.  It can be difficult to test all of the cases so having feedback from others is extremely helpful/useful.
