### ISSUE TITLE
Subdirectories not found/created

### ISSUE THREAD

**Issue by wbuchanan** [wbuchanan/brewscheme#36]
@tiemann confirmed fix for `filesys` but still had issues with other packages executing correctly.  See comment here: https://github.com/wbuchanan/brewscheme/issues/21#issuecomment-173272921.

**Comment by wbuchanan** [comment]
The source on the distribution page was outdated and not being merged with the changes that were being pushed into dev.  There are possibly a few unresolved merge conflicts related to the Java binaries, but all merge conflicts in the Stata code have been resolved:

```
. net inst brewscheme, from("http://wbuchanan.github.io/brewscheme/")
checking brewscheme consistency and verifying not already installed...
installing into c:\ado\plus\...
installation complete.

. brewcolordb, ref
This program needs to clear all data currently in memory. If this is ok hit enter, otherwise enter the letter 'n' and hit enter to exit the program 
> without clearing data from memory.. 
(142 real changes made)

. brewscheme, scheme(punk1) allst(purples)
The directory c:\ado\personal/b was successfully created.


For bugs/issues, please submit issues to: 
http://github.com/wbuchanan/brewscheme
For additional information about the program visit: 
http://wbuchanan.github.io/brewscheme
```

**Comment by wbuchanan** [comment]
And in case you were wondering what the graphs with this scheme look like:

```
sysuse auto.dta, clear
tw scatter price weight if foreign == 0 || scatter price weight if foreign == 1, scheme(punk1)
```

![troubleshootingexample](https://cloud.githubusercontent.com/assets/5542790/12457964/ebfe93a0-bf6c-11e5-91ef-661e96113b46.png)

**Comment by tiemann** [comment]
Confirming your fix. Terrific support - everything works well now (on Win10).

**Comment by wbuchanan** [comment]
@tiemann glad to hear that.  Debugging for Windoze tends to be the thing I forget about the most.  Thankfully I get reminders when users discover those issues and then I remember to check things a bit more thoroughly.
