### ISSUE TITLE
brewscheme db

### ISSUE THREAD

**Issue by Hemken** [wbuchanan/brewscheme#37]
Looks like you've already fixed the url for colorbrewer2.org.  However, this hasn't gotten into the version on SSC?

**Comment by wbuchanan** [comment]
@Hemken That is correct.  I've been waiting to finish up an article to submit to the Stata Journal that would coincide with a version 1.0 release.  However, you should be able to use:

```
net inst brewscheme, from("http://wbuchanan.github.io/brewscheme") replace
```

To get the most current version available.  It would probably also be a good idea to first find the existing version and uninstall it:

```
ado, find(brewscheme)
ado uninstall [#]
```

Where the `#` symbol would be the value returned by the first command.  Unless anyone notices any bugs the version that would be installed is the version that will end up being the 1.0 release (and at the moment, the only remaining work is documentation for `brewtheme`).  Hope this helps.

**Comment by Hemken** [comment]
Thanks.  I have a researcher who is looking for "better colors than the default", and thought of your Stata Conference presentation.  Found the error, poked through the code, thought I would fork it an fix it ... but I'll just play around with the dev version instead, since it should be ready to go.  I'll let you know if I stumble on any problems, of course.

**Comment by wbuchanan** [comment]
I think it was just a matter of changing the protocol from http to https to avoid getting an error from a page redirect.  There is quite a bit more capabilities in the dev version compared to what I talked about in Ohio.  There is a separate command for dealing with aesthetics that are generally graph independent `brewtheme` that helps to modularize things a bit.  So you could create a theme file that imitates the ggplot2 characteristics (e.g., grid lines, grey background, legend on the right side, etc...) and use that with different color schemes.  There are a few other tools as well (e.g., something to convert hex to RGB values, color interpolation, installing new named color styles, etc...).  The biggest thing (and the one I was most wanting to accomplish) is `brewproof` which takes your graph command and returns a proof copy that shows how it would look to individuals with different forms of color sight impairments.  If there are any places where you think the examples/documentation could be fleshed out a bit more (aside from the obvious lack of help file material for brewtheme) let me know and I can try to get it worked in before submitting the version 1 release to Kit.

**Comment by wbuchanan** [comment]
@Hemken I'll be sending Kit a new version later this week, but the master and dev branches are both up to date now and the project page will have the latest versions (most differences are just setting the distribution dates and version numbers) within the next day or two (depending on how quickly I can get everything merged).

**Comment by wbuchanan** [comment]
@Hemken the version 1.0 release is now available from the SSC archives so you should be able to: 

```
ssc inst brewscheme, replace
```

To get what was likely installed from the development branch previously (but this will have updated and better documentation).

**Comment by Hemken** [comment]
Thanks!

## 

Doug Hemken
4226I Social Science Bldg.

dehemken@wisc.edu
262-4327

To make a consulting appointment send me an email, or use the on-line scheduler:
https://calendar.wisc.edu/scheduling-assistant/public/profiles/PlRxCykH.html

**Comment by wbuchanan** [comment]
@Hemken Not a problem.  The project page has also been completely rebuilt so users can view all of the help files via the project pages now (including a few embedded examples when/where practical).  I'm also going to try being a bit more proactive about building out some new examples when responding to graph queries on StataList.
