### ISSUE TITLE
brewscheme with spmap

### ISSUE THREAD

**Issue by ealda** [wbuchanan/brewscheme#39]
Dear William
Thank you very much for your awesome package.
is it possible to use brewscheme with spmap for choropleth maps. I have tried and i can't get it to work. I would like to get different shades of purple in a map. 
Thank you

**Comment by wbuchanan** [comment]
@ealda can you send an example of what you tried?  Scheme files are independent of the graph commands so I'm not sure why it would behave differently from expected.

**Comment by wbuchanan** [comment]
@ealda from `help spmap`

```
 twoway_options                     any options documented in [G] twoway_options, except for aspect_option,
                                           scheme_option, by_option, and advanced_options
```

It doesn't look like it is anything that I can deal with on my side of things.  Maybe connect with Maurizio Pisati to ask if the package is still being maintained and if so what the possibility is to allow a scheme passthru option?

**Comment by ealda** [comment]
thank you very much. will follow with Pisati

**Comment by wbuchanan** [comment]
@ealda not a problem.  If there's anything I can do to help out with the spmap stuff feel free to let Pisati know that I'm more than glad to help out where I can.
