### ISSUE TITLE
Error using in Stata 14 (colordb.dta not found) (Stata error 3598)

### ISSUE THREAD

**Issue by lucasmation** [wbuchanan/brewscheme#50]
uau, your package sounds great! Thank you. 
However, in trying to use it with Stata 14 I get an error message: 

```
*Installation
. net inst brewscheme, from("http://www.paces-consulting.org/stata")
checking brewscheme consistency and verifying not already installed...
installing into c:\ado\plus\...
installation complete.
r; t=102.96 11:37:57
```

```
* Usage: following the example in the help file
.  brewscheme, scheme(set1) allst(set1) allc(5) allsat(80)
The directory c:\ado\personal/b was successfully created.
file c:\ado\personal/brewcolors/colordb.dta not found
                 stata():  3598  Stata returned error
       brewcolors::new():     -  function returned error
            brewcolors():     -  function returned error
                 <istmt>:     -  function returned error
r(2); t=13.41 11:38:11
```

any ideas on what can be going on? 

again, congrats
Lucas

**Comment by wbuchanan** [comment]
@lucasmation you might have better luck installing directly from the project page:

``` Stata
net inst brewscheme, from("http://wbuchanan.github.io/brewscheme/") replace
```

After installation, you need to run a command to build out the file that contains all of the palette information.  The full instructions can be found on the [project page](https://wbuchanan.github.io/brewscheme/).

**Comment by wbuchanan** [comment]
@lucasmation did installing from the project page solve this for you or are you still having issues with the installation?

**Comment by lucasmation** [comment]
not really.  I ran: 

```
net inst brewscheme, from("http://wbuchanan.github.io/brewscheme/") replace
checking brewscheme consistency and verifying not already installed...
all files already exist and are up to date.

```

and then:

```
. brewscheme, scheme(set1) allst(set1) allc(5) allsat(80)
file c:\ado\personal/brewcolors/colordb.dta not found
                 stata():  3598  Stata returned error
       brewcolors::new():     -  function returned error
            brewcolors():     -  function returned error
                 <istmt>:     -  function returned error

```

**Comment by wbuchanan** [comment]
You need to build the dataset with the color palette data before you can create a scheme file.  I'm not sure how much of the error you're getting is a function of that vs installation issues.  Did you check out the installation instructions on the [project page](http://wbuchanan.github.io/brewscheme/about/)?  

After installing you should have run

``` Stata
brewcolordb, rep
```

To build out the file with the color palettes (e.g., the file that cannot be found in the error message above).  If that file does not exist, the `brewscheme` command will fail every time.

**Comment by wbuchanan** [comment]
@lucasmation-zz just wondering if the last response resolved the issue for you.

**Comment by wbuchanan** [comment]
@lucasmation haven't heard back from you on this one, so I'm assuming the last bit of advice solved things and I'm going to close this ticket.  If the issue persists feel free to reopen this ticket (instead of creating a new one).
