### ISSUE TITLE
Offer predefined themes

### ISSUE THREAD

**Issue by cschwem2er** [wbuchanan/brewscheme#51]
Hi,

first of all many thanks for creating such an awesome Stata package. Visualization is one of the few areas where (until now) Stata needed to improve and `brewscheme` is an excellent option for this.

From my impression, due to the extensive functionalities `brewscheme` does offer, this can easily appear overwhelming at first sight. I would for example not have enough time to show students the full package in a Stata course fo rbeginners. Have you considered to add a couple of default theme+scheme combinations?
For some people who are just looking for an easy way to improve graphic defaults, this would be a very nice addition. All others could still get more involved and use the full functionalities of `brewscheme`.

Cheers,
Carsten

**Comment by wbuchanan** [comment]
@methodds there are a couple examples on the [project page](https://wbuchanan.github.io/brewscheme/) that show how to recreate the s2color scheme and a scheme that looks similar to ggplot2.

**Comment by cschwem2er** [comment]
Hi,

yes I know, but default themes and examples are a different thing. Thanks anyway :)

**Comment by wbuchanan** [comment]
@methodds Could you provide some ideas of what you were thinking of?  I could package a .do file that would build the scheme files with the package, but including themes with it seems to defeat the primary purpose of the program.

**Comment by wbuchanan** [comment]
@methodds To be clear, I'm not opposed to what I think your major premise is (e.g., make it easier for naïve users to get up and running with things) and agree that it can be overwhelming.  Do you think something like a tutorial might satisfy this and if so do you have any ideas about what might make things easier for your students?  There is a .do file (themefiledata.do if I remember the name correctly at the moment) that builds out a dataset used to write the theme files.  These aren't really helpful on their own and aren't recognized directly by `Stata`.  Instead, they write out the syntax related to those parameters and are basically copy and pasted into the scheme files when they are created (e.g., a read only stream gets opened and then specific lines from the file get read and inserted into the scheme files).  

One of the biggest challenges with the theme file stuff was that there isn't documentation available for all of the parameters that could be used to make a really clear documentation on my end.  That was the primary reason why I created the helpfile(s) for `brewtheme` with so many links to the existing documentation and/or references to specific lines in the `s2color` scheme.

**Comment by cschwem2er** [comment]
Hi William,

from my point of view your package already is excellent to fulfill it's primary goal: enabling stata users to create plotting schemes for their individual needs. Your article for the Stata journal describes this in great detail.

But I think that your package could also fulfill the needs of users who are a) Stata beginners and cannot be confronted with too much syntax or b) Stata users who just want a very easy method for more modern looking schemes without much effort. For this you would really need a couple of ready-to-go schemes that you ship with the installation of your package.
This would be similar to [ggthemer](http://www.shanelynn.ie/themes-and-colours-for-r-ggplots-with-ggthemr/) and for the enduser would be as simple as

```
net inst brewscheme, from("http://wbuchanan.github.io/brewscheme/")
set scheme bs_categorical, permanently
```

As an additional benefit, this could act as a nice and easy way to show users what is possible with `brewscheme`.

Cheers,
Carsten

Edit: Just on a sidenote, I am very impressed by the [seaborn](https://github.com/mwaskom/seaborn) package for Python, which is my preferred package for data visualization at the moment. Maybe one could copy some concepts from it.

**Comment by wbuchanan** [comment]
@methodds 

That makes sense.  One of the things that I was hoping would happen is the creation of a repository where users could upload schemes they've created and then other users could simply install selected schemes (something analogous to using `devtools::install_github()` in R but specifically for schemes).  I also need to make sure I keep the number of files on the smaller side since .pkg files have some built in limits with the number of files they will support.  For example, the installation for libhtml only places an .ado file on the machine and running that is what actually handles downloading and installing all of the Mata code on the users machine.  One of the suggestions from the article reviewer was to potentially create a dialog as well.  I've not had success with dialogs in the past but could definitely see the value in it and how it would make things a bit easier for newer users.  I'm just starting a new job and have a lot more work to prep things for the conference later this month, but I should be able to get something like this set up in the not to distant future.

**Comment by cschwem2er** [comment]
I think besides some schemes shipped out of the box a repository where users could upload their own schemes is an excellent idea! :)

**Comment by wbuchanan** [comment]
I started trying to build out a Java plugin to handle interfacing with Git and GitHub a while ago and will try to move that up a bit higher in the priority list.  Essentially it would be a program analogous to `devtools` in `R`, but with Stata in mind.  Part of what I got stuck on was building a decent parser that I could use to translate something like JavaDoc comments into SMCL so helpfiles could be created from comments in the source code as well.  If you have any experience working with ANTLR I could definitely use a bit of help with that.

**Comment by wbuchanan** [comment]
I'm thinking I might do this as a separate package now (e.g., brewschemeextras) to make it a bit easier to maintain and prevent this project from getting too cluttered.  I'll try to throw something together in the next week or so and would definitely like it if you and/or anyone you know could help with testing things (e.g., installing and making sure the schemes work with your graph commands).

**Comment by wbuchanan** [comment]
@methodds Just set up a quick test site using some scheme files I created for a talk I did earlier this year.  You should be able to install the scheme files using:

``` Stata
net inst brewschemeExtras, from("https://wbuchanan.github.io/brewschemeExtras/")
```

Then you can use `scheme(sdp2016a)`, `scheme(sdp2016a2)`, `scheme(sdp2016b)`, or `scheme(sdp2016b2)` in graph commands and it should use the appropriate scheme (there are fairly subtle differences between them).  If that works I can clean things up a bit and push the examples I had worked on putting together for the SJ article and building out some contribution guidelines and things like that.

**Comment by wbuchanan** [comment]
@methodds haven't heard back yet, so I'm assuming the other repository works as a way of fulfilling this request and will close the issue.  If it doesn't work for you feel free to reopen the ticket.
