### ISSUE TITLE
file http://colorbrewer2.org/colorbrewer_schemes.js not found

### ISSUE THREAD

**Issue by aarondwolf** [wbuchanan/brewscheme#59]
This error was reported before, but it seems to have come up again. Here is my code. I just installed today from Git, so I don't think the out of date issue applies, but maybe I did something wrong:

`/* 	Install Brewscheme`
`	net inst brewscheme, from("http://wbuchanan.github.io/brewscheme/") replace`

`// Next build out the color database (which also creates color blind translations of the Stata named color styles)`
`	set scrollbufsize 2048000`
`	set trace on`
`	brewcolordb, replace override`
` `
`// If you've previously installed brewscheme, you'll also need to rebuild the look up data set used by brewscheme`
`// to build the scheme files (the difference is that this file will now also include the color sight impairment simulation values)`
`// You can also accomplish the step above this by passing the refresh option to brewscheme`
`	brewdb, replace`
`*/`

The error I get is after brewdb:

`.         brewdb, replace`
`Directory exists and rebuild option not specified.  No further action`
`file http://colorbrewer2.org/colorbrewer_schemes.js not found`
`server says file permanently redirected to https://colorbrewer2.org/colorbrewer_schemes.js`
`r(601);`

This is fixed by editing line 59 of the `brewdb.ado` file (where it copies the js file from the website) to use https instead of http:

`			// Read the javascript into memory`
`			qui: copy "http://colorbrewer2.org/colorbrewer_schemes.js" 	 ///   `
`			`brewjs'.js`

Changes to:

`			// Read the javascript into memory`
`			qui: copy "https://colorbrewer2.org/colorbrewer_schemes.js" 	 ///   `
`			`brewjs'.js`

Re running works:
`.         brewdb, replace`
`Directory exists and rebuild option not specified.  No further action`
` `
`.  `
`end of do-file`

**Comment by wbuchanan** [comment]
@aarondwolf,

Thanks.  It's really odd that this issue has come up again, but should be a fairly quick/easy fix.

**Comment by wbuchanan** [comment]
@aarondwolf 
This issue should be fixed now and the fix should be available to users installing `brewscheme` from the GitHub pages location (https://wbuchanan.github.io/brewscheme).
