### ISSUE TITLE
Failure to remove personal/b directory at first run

### ISSUE THREAD

**Issue by davideyre** [wbuchanan/brewscheme#7]
See log below

Delete the file brewmeta.dta from ~/Library/Application Support/Stata/ado/personal/b ? (Y/n). Y
    - if inlist(`"`del'"', "y", "Y", "") {
    = if inlist(`"Y"', "y", "Y", "") {
    - erase`"`path'/`: word `i' of`dirfiles''"'
    = erase `"~/Library/Application Support/Stata/ado/personal/b/brewmeta.dta"'
    - di as res`"Erased the file : `path'/`: word `i' of`dirfiles''"'
    = di as res `"Erased the file : ~/Library/Application Support/Stata/ado/personal/b/brewmeta.dta"'
Erased the file : ~/Library/Application Support/Stata/ado/personal/b/brewmeta.dta
    - }
    - }
    - loc dirfiles : dir`"`path'"' files "*", respectcase
    = loc dirfiles : dir`"~/Library/Application Support/Stata/ado/personal/b"' files "_", respectcase
    - loc subdirs : dir `"`path'"' dirs "_", respectcase
    = loc subdirs : dir `"~/Library/Application Support/Stata/ado/personal/b"' dirs "*", respectcase
    - if`"`dirfiles'`subdirs'"' == "" {
    = if `""' == "" {
    - di as res`"`path' is empty.  Delete the directory too? (Y/n)"' _request(_del)
    = di as res`"~/Library/Application Support/Stata/ado/personal/b is empty.  Delete the directory too? (Y/n)"' _request(_del)
~/Library/Application Support/Stata/ado/personal/b is empty.  Delete the directory too? (Y/n). Y
    - if inlist(`"`del'"', "y", "Y") {
    = if inlist(`"Y"', "y", "Y") {
    - qui: rmdir`"`i'"'
    = qui: rmdir`""'
invalid syntax
      }
      }
      }

**Comment by wbuchanan** [comment]
Redirected to function repository https://github.com/wbuchanan/dirfile/issues/1
