### ISSUE TITLE
file handle error - "file handle scheme already exists"

### ISSUE THREAD

**Issue by davideyre** [wbuchanan/brewscheme#8]
"file handle scheme already exists" error on calling: brewscheme, scheme(set1) allst(set1) allc(8) 

...
- if !inlist(`somesaturation', 0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 200) {
  = if !inlist(100, 0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 200) {
    if`somesaturation' <= 104 {
    loc somesaturation = round(`somesaturation', 10)
    }
    else if`somesaturation' > 104 {
    loc somesaturation 200
    }
    else {
    di "Setting some saturation to 100"
    loc somesaturation 100
    }
    }
- qui: file open scheme using `"`c(sysdir_plus)'/s/scheme-`schemename'.scheme"', w replace
  = qui: file open scheme using`"~/Library/Application Support/Stata/ado/plus//s/scheme-set1.scheme"', w replace

file handle scheme already exists

**Comment by wbuchanan** [comment]
For errors listing that the file handle already exists it is the result of a previously unsuccessful call to the program that did not close the file connection.  You can use:

```
file close _all
```

To close any open file connections in these cases.  I've added a bit to brewscheme.ado that I'll need to test a bit to attempt closing the file connection at the start of the program to avoid these issues for users in the future.

**Comment by wbuchanan** [comment]
Added code to attempt closing the file connection (and capturing the return code of the file connection is not open) to the start of the program.

**Comment by wbuchanan** [comment]
User emailed to confirm program is operating as expected.
